### PR TITLE
Fixes #122 - Added a new container to avoid duplicate code

### LINKED ISSUE #122: adding new container to avoid duplication between graphics
Right now, we duplicate code when we add another graphic. It would be relevant to add a new container to handle configuration required for new graphic.

### PR DESCRIPTION
**Pull request by magsout**
The main goal of this PR is to improve the code base, to make easier the way to add a new Chart and improved the code base globaly by for example removing Redux which is not very necessary for now in this project.

Before to add a new Chart we had to do https://github.com/webcompat/webcompat-metrics-client/pull/111/files

With the new container `<MetricsTemplate />` we would have written for `weeklyreport`:

```js
const WeeklyReports = () => {
  return (
    <MetricsTemplate
      endpoint={"needsdiagnosis-timeline"}
      title={"Needs diagnosis dashboard"}
      subtitle={"Tracking issue diagnosis burndown rate"}
      normalizeData={handleData}
      renderChart={data => (
        <LineChart
          title={"Open issues in needsdiagnosis milestone"}
          label={""}
          labels={ObjectNested.get(data, "chart.dates", [])}
          legend={{ display: false }}
          data={ObjectNested.get(data, "chart.openIssues", [])}
          options={{
            scales: {
              xAxes: [
                {
                  type: "time",
                  distribution: "linear",
                },
              ],
            },
          }}
        />
      )}
    />
  );
};
```

We have the ability to add functions to normalize and the graph that we want. We can disable `Header`, `Jumbotron`, `SimpleStat`. We can add new filters in addition of the `CommonFilters` or add new filters and disabled `CommonFilters`.

I removed `Redux` because I find it is not necessary for now.

And I added news test and improved the coverage of the tests.

r? @miketaylr

### CODE REVIEW

**Comment by magsout** [comment]
Don"t understand why `circleci` failed. Why it fails with Prettier. I updated `Prettier` locally and tests passed.

**Comment by magsout** [comment]
Cool, tests passed. 

@miketaylr do not forget to update news deps.

**Comment by miketaylr** [comment]
> This branch has conflicts that must be resolved

@magsout want to fix this up, then merge?

**Comment by magsout** [comment]
@miketaylr I want to merge this PR first https://github.com/webcompat/webcompat-metrics-client/pull/138 the conflicts are a pain because the architecture is different

**Comment by magsout** [comment]
@miketaylr done, waiting for tests.

**Comment by magsout** [comment]
Green.

**Comment by magsout** [comment]
@miketaylr let's merge.

**Comment by miketaylr** [comment]
🎉

**Pull request merged**
