### PR TITLE
Next.js migration

### PR DESCRIPTION
**Pull request by magsout**
Why migrate to Next.js -> https://nextjs.org/learn/basics/getting-started
- React framework
- SSR (Server Side Rendering, useful for the future?)
- no more React Router 
- simple configuration (remove webpack configuration)

Before
Screen Shot 2020-04-05 at 18 22 20

After:
Screen Shot 2020-04-05 at 18 22 55

### CODE REVIEW

**Comment by magsout** [comment]
@karlcow is it possible to get the log:

Screen Shot 2020-03-29 at 17 55 54

**Comment by karlcow** [comment]
This is strange.

**Comment by karlcow** [comment]
@magsout done.

**Comment by miketaylr** [comment]
@laghee are you able to see logs to help here?

**Comment by miketaylr** [comment]
I want to add @ksy36 to the review, she knows more React than I do. :)

But I'll also take a look!

**Comment by magsout** [comment]
>It seems like a lot of the changes here are Prettier changes, in the future it would be nice to do a commit for the functional changes, then a commit for the style changes (that way it's easier to ignore those :P)

oups, I can make a commit for Prettier if you want.

**Comment by magsout** [comment]
thanks @miketaylr @ksy36

**Pull request merged**
