### PR TITLE
fixes #131 - moving to BarChart

### LINKED ISSUE #131: Investigate setting horizontal axis on Weekly Reports to always use week (pref. Monday) increments
Right now, the x-axis shows differing date increments depending on how large the range is. When it's set to a month (like the default), for example, it displays 2-day increments (which for weekly reports doesn't make sense since the number only changes Mondays):
screenshot 2018-12-06 12 19 41
A couple of weeks means you get timestamps, which makes even less sense for weekly reports (where the time is set to midnight):
screenshot 2018-12-06 12 19 12

Hopefully there's a way to fix this without too much trouble.

### PR DESCRIPTION
**Pull request by magsout**
I tried several configurations

What do you think ?

@miketaylr it's better to display data like this?

### CODE REVIEW

**Comment by magsout** [comment]
Deployed there https://webcompat-dashboard-pr-138.herokuapp.com if you want to see the result

**Comment by miketaylr** [comment]
> Deployed there https://webcompat-dashboard-pr-138.herokuapp.com/weeklyreports?from=2018-11-12&to=2018-12-12 if you want to see the result

Ooops, that links seems down. @magsout is there a way to generate a new one to see?

**Comment by magsout** [comment]
@miketaylr yes 
https://webcompat-dashboard-pr-138.herokuapp.com/?from=2018-11-17&to=2018-12-17

**Comment by miketaylr** [comment]
screen shot 2018-12-17 at 2 10 56 pm


I agree that a bar chart is a pretty good way to present this data. For just 4 weeks it feels a bit odd, but if you widen the view to like 8+ weeks it looks much better.

screen shot 2018-12-17 at 2 13 41 pm

Also, is it possible to display a label of the weekly value without needing to hover?

**Comment by karlcow** [comment]
>  label of the weekly value
I wonder if @miketaylr is talking about the number of issues.

**Comment by miketaylr** [comment]
> I wonder if @miketaylr is talking about the number of issues.

yes, sorry. that was *very* unclear. :)

**Comment by magsout** [comment]
it seems the option does exists https://www.chartjs.org/samples/latest/advanced/data-labelling.html

**Comment by magsout** [comment]
the method to add a new plugin with React wrapper for Chart.js 2 https://github.com/jerairrest/react-chartjs-2#chartjs-object

**Comment by magsout** [comment]
@miketaylr then, I updated the PR with this following list:

- initial filters:  8 weeks between from and to
- initial filters: every weeks begin Monday
- disabled tooltip
- added number of issue on top of every bar

**Comment by magsout** [comment]
The last thing is about the first and last bar which are overflow the graph:

capture d ecran 2019-01-03 a 08 57 56


I don't know how to fix that.

**Comment by magsout** [comment]
@miketaylr thanks

**Pull request merged**
