### PR TITLE
fixes #32 - added travis configuration

### LINKED ISSUE #32: Add travis or circleci

### PR DESCRIPTION
**Pull request by magsout**

### CODE REVIEW

**Comment by magsout** [comment]
r @miketaylr ?

I use circleci not travis, just to be sure my configuration is enought?

The failed is logic and normal

**Comment by miketaylr** [comment]
> I use circleci not travis, just to be sure my configuration is enought?

@magsout we can use CircleCI - I just started using it for 2 moz projects:

https://github.com/mozilla/webcompat-blipz-experiment/blob/master/.circleci/config.yml

**Comment by miketaylr** [comment]
https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

What you have is fine, it's just missing a command to install npm deps, and run any tasks or tests:

See 
install: 

https://github.com/webcompat/webcompat.com/blob/master/.travis.yml#L42

script:
https://github.com/webcompat/webcompat.com/blob/master/.travis.yml#L60

**Comment by miketaylr** [comment]
Um, apparently I'm just wrong, because https://travis-ci.org/webcompat/webcompat-metrics-client/builds/376497941?utm_source=github_status&utm_medium=notification exists. So I guess it figured out how to install a package.json and run tests by itself by default?

**Comment by miketaylr** [comment]
> The failed is logic and normal

@magsout to clarify, you're saying you expect the tests to fail right now, right?

**Comment by magsout** [comment]
@miketaylr 
>. So I guess it figured out how to install a package.json and run tests by itself by default?

yes, by default with node, travis runs `npm install` && `npm run test`

>@magsout to clarify, you're saying you expect the tests to fail right now, right?

yes, I don't add any script to install dep for the client, so every packages are not found when travis runs the test.

**Comment by miketaylr** [comment]
> yes, by default with node, travis runs npm install && npm run test

TIL, thanks.

**Pull request merged**
