### PR TITLE
Fixes #172  - webcompat.com dashboard triage

### LINKED ISSUE #172: Move webcompat dashboard
After an email to @miketaylr and a talked with @karlcow on irc. 

It's possible to called an endpoint on webcompat to keep back the data.

Here the fonction on webcompat : https://github.com/webcompat/webcompat.com/blob/cc35b31a6246d91c39c46522448614916da64e93/webcompat/views.py#L514-L525 and the endpoint https://webcompat.com/api/issues/category/needstriage?per_page=100

What we need to do:
- handle pagination on JavaScript side
- handle filters on JavaScript side https://webcompat.com/dashboard/triage
Capture d’écran 2019-05-01 à 10 25 02
- add a reducer to mimik this function https://github.com/webcompat/webcompat.com/blob/cc35b31a6246d91c39c46522448614916da64e93/webcompat/dashboard.py#L17-L47

@miketaylr 
- what do you think? 
- is it revelant to work on it and moving the dashborad?
- is CORS are allowed on webcompat.com ?
- do you at first add back completly the same thing on webcompat?

### PR DESCRIPTION
**Pull request by magsout**
first shot. I need to improve test..

### CODE REVIEW

**Comment by miketaylr** [comment]
Adding @laghee as a reviewer, because she's more familiar than I am with this codebase at this point. :)

**Comment by magsout** [comment]
oups, ....

**Comment by magsout** [comment]
@laghee failed fixed

**Comment by laghee** [comment]
Cool! LGTM -- back to just that weird `eslint` stuff. 👍

**Comment by magsout** [comment]
mheeeu :(

**Comment by magsout** [comment]
@laghee done... GREEEN 💃

**Pull request merged**
