### PR TITLE
Fixes #140 - Add needscontact dashboard

### LINKED ISSUE #140: Add Contact Dashboard

### PR DESCRIPTION
**Pull request by laghee**
OK, client-side dashboard 2 of 3... As always, let me know if I missed or need to improve anything, @magsout.

### CODE REVIEW

**Comment by laghee** [comment]
Oh, rats. I checked out this branch directly from the other one. Let me fix the weird commit history...

**Comment by magsout** [comment]
@laghee 

two options:

1) edit the PR and change the source of branch
2) rebase

**Comment by magsout** [comment]
option 1 is impossible because you already merged ;)

**Comment by laghee** [comment]
> @laghee
> 
> two options:
> 
>     1. edit the PR and change the source of branch
>     2. rebase

Thanks to your super-fast response time, @magsout -- I got to do the easy rebase instead of going through a tedious interactive one... 😜

**Comment by laghee** [comment]
oops, but something is failing...

**Comment by laghee** [comment]
Huh... I think I maybe found a bug? @magsout, when you updated the packages to fix the security warnings, you added some extra dashes before one of the params in the npm `jest` script. Are these intentional?
Screenshot 2019-03-29 11 34 36

I'm getting this error locally when I try to update snapshots:
Screenshot 2019-03-29 11 35 38

**Comment by magsout** [comment]
@laghee ooups.. good catch. 

>maybe I need to alter it now that the test script has changed?):

yes, please :D

**Comment by laghee** [comment]
OK, this is weird. I deleted two of the dashes, but I still get the `unrecognized parameter` error. Taking out the `detectOpenHandles` parameter makes everything happy. 🤔 

Seems like it should work fine, though, according to the docs (https://jestjs.io/docs/en/cli.html#detectopenhandles)... unless there's something about the `async_hooks` requirement that's causing problems?

**Comment by magsout** [comment]
works fine for me. I re-add `detectOpenHandles`

```
    "test:jest": "jest --runInBand --detectOpenHandles --coverage --forceExit",
```

and run `npm run test:jest -- -u`

**Comment by laghee** [comment]
Hmm. OK, I blew something up. Maybe the "easy" rebase was too "easy"?? 🤦‍♀️ 

I'll go look more closely at the changes and see what I might have accidentally altered.

**Comment by magsout** [comment]
@laghee you rebase is perfect (I pulled your branch, but maybe something about the NPM update dep?)

I can push a fix on your branch if you need

**Comment by laghee** [comment]
@magsout Aha! Yes! Ran `npm install` again, got the tests to fail the same way as in the CI, updated the snapshots again, and ... (maybe?) fixed all the weirdness. 🤞 🤞 🤞

**Pull request merged**
