### PR TITLE
fixes #167 - fixed x-axis labels

### LINKED ISSUE #167: The x-axis labels are incorrect for the need-striage, needs-contact and site-wait graphs
Right now they alternate between 1 AM and 1 PM, when they should be more like the dates in needs-diagnosis.

### PR DESCRIPTION
**Pull request by magsout**

### CODE REVIEW

**Comment by magsout** [comment]
@miketaylr to avoid this x-axis render (https://webcompat-dashboard.herokuapp.com/needstriage?from=2019-05-08&to=2019-05-10), I forced unit on day. I don't know if hour unit is revelant or not?

**Comment by miketaylr** [comment]
(note: https://webcompat-dashboard-pr-168.herokuapp.com/ doesn't work, is that known?)

**Comment by magsout** [comment]
@miketaylr yuip, every PR branch deployed is limited to 7 days. After that 💥

**Comment by miketaylr** [comment]
Ah, cool Good to know :)

**Pull request merged**
