### PR TITLE
Fixes #85 - Add triage dashboard

### LINKED ISSUE #85: Add Triage Dashboard
Can we extend the NeedsDiagnosis Graph Dashboard to Triage as well?
I think it would be interesting to see the pattern of the Triage activity, and maybe learn something from this.

https://webcompat.github.io/webcompat-metrics-client/?from=2018-05-01&to=2018-07-12

Maybe something like this?
image

### PR DESCRIPTION
**Pull request by laghee**
Let me know if I did this correctly, @magsout. The endpoint doesn't exist yet because I need to get that done server-side, so maybe that's why I can't see a new dashboard tab when I run it locally?

Maybe I should have waited until I had all the endpoints lined up, but I wanted to be sure I knew how to use the new super-simple container correctly in the meantime... 😍

### CODE REVIEW

**Comment by magsout** [comment]
@laghee to see the item in the menu, you have to add the link under https://github.com/webcompat/webcompat-metrics-client/blob/master/src/layouts/index.js#L19

**Comment by magsout** [comment]
>Maybe I should have waited until I had all the endpoints lined up, but I wanted to be sure I knew how to use the new super-simple container correctly in the meantime... 😍

ah ah ah thanks <3

**Comment by laghee** [comment]
> @laghee to see the item in the menu, you have to add the link under https://github.com/webcompat/webcompat-metrics-client/blob/master/src/layouts/index.js#L19

Aha!

...OK, I tried importing the container and adding the link:
Screenshot 2019-03-21 00 14 06

But I'm still not seeing anything in the menu:
Screenshot 2019-03-21 00 14 47

Ah, wait! Looks like I needed to add a link here, too: https://github.com/webcompat/webcompat-metrics-client/blob/7303699a8aaabf85cdc95590a254dabf6c5c48e8/src/containers/Navigation/index.js#L51

Yep, OK, now we're in business:
Screenshot 2019-03-21 00 34 46

Thanks, @magsout! I'll get this set up on the server and update the test data, and then, I think?, we should be good to go.

**Comment by magsout** [comment]
If I may, the only thing missing is a small test for NeedsTriage 😘

**Comment by laghee** [comment]
@magsout, I added a test, but I'm getting weird `eslint` errors locally when I run all the tests (maybe related to this? -- https://github.com/AtomLinter/linter-eslint/issues/1100):
Screenshot 2019-03-21 16 42 13

All the CI tests passed, so... maybe just my machine being quirky with `eslint`?

**Comment by magsout** [comment]
>All the CI tests passed, so... maybe just my machine being quirky with eslint?

yes, if CI passed, it's ok. let me also test locally.

**Comment by magsout** [comment]
@laghee 

Capture d’écran 2019-03-21 à 18 11 01



everything is good 👍

**Comment by laghee** [comment]
OK, server side PR is waiting on review from @karlcow (https://github.com/webcompat/webcompat-metrics-server/pull/99). Let me know if you think we're good to go after that, @magsout!

**Comment by magsout** [comment]
@laghee parameters `from` and `to` doesn't do anything ? the API responses are the same whatever state I choose.

**Comment by laghee** [comment]
@magsout The problem is that my script has only been collecting data since yesterday evening... so there are limited data points. I think our defaults are set up to use whatever data is available in that case. The same thing happens if you choose a range with a starting date before Feb. 2018 for NeedsDiagnosis.

I'm planning on adding some back-dated counts, but still working out the best way to do that.

**Comment by magsout** [comment]
@laghee oh ok. thanks for the explanation.

**Comment by magsout** [comment]
@laghee maybe, i can think how I can add a min-date on the from input? What do you think? (let open a new issue if needed)

**Pull request merged**
