### PR TITLE
Fixes #60 - Added widget for the most and the less number of issues within the dates

### LINKED ISSUE #60: Added two widgets for the most and the less number of issues per day

### PR DESCRIPTION
**Pull request by magsout**
Before:

screenshot-2018-6-26 webcompat-metrics-client

After:

screenshot_2018-06-26 webcompat-metrics-client

@miketaylr  @karlcow  Not sure about the words ;)

### CODE REVIEW

**Comment by karlcow** [comment]
we could put the date indeed
Min 316 (2018-06-24)

**Comment by magsout** [comment]
@karlcow thanks for you review.

**Comment by magsout** [comment]
New proposal based on the idea of @karlcow 

screenshot_2018-06-29 webcompat-metrics-client


r @karlcow @miketaylr  ?

**Comment by karlcow** [comment]
ship it!

**Comment by miketaylr** [comment]
lgtm!

**Pull request merged**
