### PR TITLE
Fixes #212 - Add TSCI to dashboards

### LINKED ISSUE #212: Add TSCI iframe chart (temp)
This is probably going to be ugly at first, but I'll give it a whirl...

### PR DESCRIPTION
**Pull request by laghee**
Still working this out, but wanted to push the first draft to have a reference point (and fix some weird merge stuff on my end). Still working on:

- server-side endpoint that grabs the `spreadsheetID`
- function to format the current `spreadsheetID`into the URL for the `iframe`

### CODE REVIEW

**Comment by laghee** [comment]
Thanks, @magsout! Now I just need to add the logic to pull out the spreadsheet ID.

**Comment by magsout** [comment]
@laghee 

> Now I just need to add the logic to pull out the spreadsheet ID  

Tell me more ?

**Comment by laghee** [comment]
@magsout 

Mike has set up an API [here](https://tsci.webcompat.com/currentDoc.json) that gives the current `spreadsheetId` string that needs to be plugged into this:
Screenshot 2019-12-08 20 43 29

Since I'm already fetching that and serving it through metrics-server here: https://webcompat-metrics.herokuapp.com/data/tsci-doc, I just need to grab that and extract the simple string. Does what I did above make any sense? (I'm not 100% clear on how to pass the parameter correctly inside the template.)

**Comment by laghee** [comment]
Also -- even though it worked before, I suddenly can't get it to display locally anymore:

Screenshot 2019-12-08 20 58 24

**Comment by laghee** [comment]
Nope, OK, that's what I figured -- I messed up. I'm passing an object instead of a string. I need to get the string out of the data object.

**Comment by laghee** [comment]
Argh. Sorry, @magsout, I need help. 😊 

I can't figure out how to access the JSON response that's coming back from the request to the server endpoint. Do I need to have a `handleData` function? I can't figure out where the `data` is or how to grab it -- when I try to pass `data` into the `framedChart` in `renderChart`, I'm only getting an empty object...

**Comment by magsout** [comment]
@laghee I pushed a proposal here https://github.com/webcompat/webcompat-metrics-client/compare/issues/212...issues/212-patch?expand=1

But I don't know why I get a cors error. @miketaylr did you do something on google docs ? I tried with another doc on my own drive, then I didn't get a cors error.

**Comment by laghee** [comment]
@magsout @miketaylr I've noticed the CORS thing, too, the last couple days, but I was hoping it was something wonky with the dev server. When I was testing with a hardcoded url before, it worked fine...

**Comment by miketaylr** [comment]
What is the CORS error? Is it coming from Google, or coming from tsci.webcompat.com?

(I can easily enable CORS headers for the latter, unsure about the former!)

**Comment by laghee** [comment]
OK, the patch works great with some tweaks, tested on my test copy of an old TSCI (https://docs.google.com/spreadsheets/d/1pe6AfG5rYtKn8AYfUr3GO0P3HT7jMNogI5D96gdTwWY/edit#gid=633060484).

But, yes, the current live TSCI spreadsheet itself is... unhappy. If I load the url in a window all on its own, the chart area is totally blank and the dates are strangely distributed over the whole year -- a couple weeks from January, some from Feb., Mar., April, then a jump to Dec.
Screenshot 2019-12-11 00 34 18

I think our framework is good, though, so I'm going to merge the patch, push my changes, and change this to an actual PR.

**Comment by laghee** [comment]
@miketaylr They're coming from Google, but I think it's because there's some kind of corruption -- it keeps trying to force from `docs.google` to `accounts.google`. (Plus the sheet itself is currently odd-looking.)

**Comment by miketaylr** [comment]
Thanks -- I'll take a peek. For fun, I just added `access-control-allow-origin: *` to the currentDoc response:  
Screen Shot 2019-12-10 at 5 41 41 PM

**Comment by miketaylr** [comment]
> But, yes, the current live TSCI spreadsheet itself is... unhappy.

Ah, I think that's expected -- the document at currentDoc.json is mostly garbage -- it's mostly me figuring out cron etc :)

Once we're "live", I'll run it again to recapture all 2019 data and manually add the graph (which will only need to be done once).

**Comment by miketaylr** [comment]
> I think our framework is good, though, so I'm going to merge the patch, push my changes, and change this to an actual PR.

🎈 🍰 awesome! nice work @laghee and @magsout

**Comment by laghee** [comment]
> > But, yes, the current live TSCI spreadsheet itself is... unhappy.
> 
> Ah, I think that's expected -- the document at currentDoc.json is mostly garbage -- it's mostly me figuring out cron etc :)
> 
> Once we're "live", I'll run it again to recapture all 2019 data and manually add the graph (which will only need to be done once).

Ahhh! OK, cool. 👍

**Comment by karlcow** [comment]
> > I think our framework is good, though, so I'm going to merge the patch, push my changes, and change this to an actual PR.
> 
> 🎈 🍰 awesome! nice work @laghee and @magsout

This is super cool to see this dashboard project mainly handled by @laghee and @magsout.
["Booyah! Aye, yo, baby I'm super duper, super dope, oh"](https://www.youtube.com/watch?v=M-p4B6PIRrI)

😍

**Comment by laghee** [comment]
@miketaylr Not sure, but maybe this super vague-sounding alleged bug (https://support.google.com/maps/forum/AAAAQuUrST8kciGR3J_Mtc?hl=lv) could have something to do with the block?

Some other similar-sounding comments:

- https://support.google.com/docs/forum/AAAABuH1jm0StVq39J3lCA?hl=zh-Hant
- https://support.google.com/calendar/forum/AAAAd3GaXpEzY8CFOiQ55U
- https://support.google.com/maps/forum/AAAAQuUrST8R17vgnERIG4?hl=fr

**Comment by magsout** [comment]
@laghee awesome. I don't merge right now. Because of https://webcompat-dashboard-pr-219.herokuapp.com/tsci? `Blocked by X-Frame-Options Policy`

**Comment by miketaylr** [comment]
> @laghee awesome. I don't merge right now. Because of https://webcompat-dashboard-pr-219.herokuapp.com/tsci? `Blocked by X-Frame-Options Policy`

Will investigate. Thanks, useful to have the preview URL.

**Comment by magsout** [comment]
@miketaylr is it a firefox issue? Its working on Chrome, on Safari 

Capture d’écran 2019-12-11 à 19 57 54

**Comment by laghee** [comment]
@magsout That makes it sound even more likely that it might be that vague Google bug I linked to in an earlier comment. Something about funky cookies or caching or whatever that results in a small percentage of authentication redirects. Don't think it's Firefox-specific because I was literally using it constantly for most of an afternoon with no problem, and then it suddenly went all X-Frame-Nope between one dev startup and the next.

**Comment by miketaylr** [comment]
For some reason `https://docs.google.com/spreadsheets/d/1SzEWbhXlJOtNes0qiY1lFy_-dCUPuMlJ7f1sCc9sdmQ/pubhtml?widget=true&headers=false&embedded=true&chrome=false` wants me to log in, so it seems like an auth thing. I can't imagine Google would want anyone to be able to frame a login flow, so it makes sense.

**Comment by miketaylr** [comment]
> @miketaylr is it a firefox issue? Its working on Chrome, on Safari

Does it work in an incognito tab? For me it works in Chrome, because I'm signed in, but fails for the same reason in a private tab.

**Comment by miketaylr** [comment]
Let me try to set the `reader` permission on the doc to `anyone`: https://developers.google.com/drive/api/v3/reference/permissions#resource

**Comment by magsout** [comment]
>Does it work in an incognito tab? For me it works in Chrome, because I'm signed in, but fails for the same reason in a private tab.

@miketaylr no..

Capture d’écran 2019-12-11 à 21 33 25

**Comment by miketaylr** [comment]
Cool, thanks. I think I fixed it, just running the script on the server to verify.

**Comment by miketaylr** [comment]
OK, all fixed. :)

We can merge now, or wait a few days for there to be actually useful data. I'm going to start a run to contain all the 2018 data now.

**Comment by miketaylr** [comment]
@magsout @laghee all merged! i assume this will auto-deploy?

**Comment by miketaylr** [comment]
(I'm not sure I have access to the dashboard on heroku, so I can't check)

**Comment by miketaylr** [comment]
Ah, it's deployed! <3

**Pull request merged**
